### ISSUE TITLE
Redesign logo

### ISSUE THREAD

**Issue by arnav-t** [arnav-t/what-slot#10]

**Comment by arnav-t** [comment]
@Sweta271097 
No problem.
If you want to work on an issue, you don't need to ask.
Just send a PR and I'll review it.

**Comment by Sweta271097** [comment]
Okay, sure.

**Comment by Sai-Adarsh** [comment]
@arnav-t you like it? gave a PR
![image](https://user-images.githubusercontent.com/21096774/49762212-24d32200-fcef-11e8-9278-9c427f570928.png)

**Comment by arnav-t** [comment]
Resolved in #27
