### ISSUE TITLE
Add an about page. 

### ISSUE THREAD

**Issue by arnav-t** [arnav-t/what-slot#11]
To be integrated with the navbar (#8)

**Comment by Sweta271097** [comment]
@arnav-t Can I get some input about what should be there in the about page?

**Comment by arnav-t** [comment]
Just add some filler text for now.
Your choice :sweat_smile: :
https://github.com/templeman/awesome-ipsum

**Comment by Sweta271097** [comment]
@arnav-t Okay.

**Comment by arnav-t** [comment]
Added in #28
