### ISSUE TITLE
Improve front-end 

### ISSUE THREAD

**Issue by arnav-t** [arnav-t/what-slot#5]
Redesign for more... elegance?

**Comment by AviBomb** [comment]
![screenshot from 2018-12-02 02-02-06](https://user-images.githubusercontent.com/38415320/49332618-691b3f80-f5d6-11e8-9603-48e6eacc80e9.png)
How would you want me to redesign the front end on similar basis to this image attached (PS: this belongs to one of my previous projects) :) Also I am open to other suggestions to make further changes to make it look better so feel free to let me know

**Comment by arnav-t** [comment]
I think you should look into Bootstrap. 
Check out the current design which is hosted at https://what-slot-kgp.herokuapp.com/
If you think you can make it look better than this, feel free to open a PR.

**Comment by arc9693** [comment]
Is this issue being worked upon by @AviBomb specifically...or i can look into it? @arnav-t

**Comment by arnav-t** [comment]
Feel free to work on it @arc9693 
Also, please join the Gitter channel: https://gitter.im/WhatSlotChat/Lobby

**Comment by Sweta271097** [comment]
Hello, 

Is this issue assigned to someone?
I would really like to work on it.

**Comment by arnav-t** [comment]
@Sweta271097 
No, it isn't. Multiple people can work on the same issue (especially on this one, since this is such a broad one).
Please feel free to start working on it.
Join the Gitter room too.

**Comment by ReenaSingh07** [comment]
can i work with this?

**Comment by arnav-t** [comment]
@ReenaSingh07 Sure, but since KWoC has ended I won't be able to provide as much support.
However, feel free to work on it in the spirit of open source. I'll try to help out from time to time whenever I find the time.
